### ISSUE TITLE
Camera crashes during incoming call while recording a video (green lense)

### ISSUE THREAD

**Issue by xetz** [CyanogenDefy/android_device_motorola_jordan#61] opened 2011-07-12 18:01 UTC
While i was recording a video a friend called me, after the call the camera software crashed. I needed to reboot, to fix it. furthermore the video file wasn´t useable. I got the cm7 rc1v2 mod, would be cool if somebody could fix this.
nevertheless this mod is awesome fast, thx!

mfG xetz

cm7 rc1v2

**Comment by maniac103** [comment] 2011-08-26 11:44
Dupe of #34.

**Closed as completed by maniac103** 2011-08-26 11:44 UTC
