### ISSUE TITLE
Can't enable root permission for ES File Explorer on latest nightly

### ISSUE THREAD

**Issue by elguaxo** [CyanogenDefy/android_device_motorola_jordan#144] opened 2011-11-06 05:49 UTC
After installing a new nightly I edit the first line of /etc/gps.conf from NTP_SERVER=europe.pool.ntp.org to NTP_SERVER=ar.pool.ntp.org
I use ES File Explorer for this. I enable "Root Explorer" and "Mount File System" under its Root settings, edit /etc/gps.conf and finally disable  ES File Explorer's "Root Explorer" and "Mount File System".

After installing the latest nightly, cm71-111106.0217-NIGHTLY-Defy, I get a "Sorry, test failed. This feature cannot run on your phone." error when trying to enable ES File Explorer's "Root Explorer" feature.

I used Yaffs Explorer this time to edit gps.conf, but I wonder why I can't enable the Root feature on ES File Explorer. My workflow worked fine till cm71-111105.0200-NIGHTLY-Defy. Any hints? TIA!

**Comment by tpruvot** [comment] 2011-11-06 06:22
yep, i can reproduce this... will fix it soon, ive made a test which will be reverted about shells

**Comment by elguaxo** [comment] 2011-11-06 06:25
Great! Thanks for your quick answer.

**Comment by tpruvot** [comment] 2011-11-06 06:34
i close the issue for the moment, was an experimental stuff already reverted some hours ago :)

**Comment by tpruvot** [comment] 2011-11-06 09:07
are you sure it was working before ? i reversed the commit and seems to fails too :/

superuser entry is authorized, but it was not enabled on my phone... ive this explorer since some time

**Comment by elguaxo** [comment] 2011-11-06 16:42
Absolutely sure! I do it each and every time after installing a nightly and it worked fine till cm71-111105.0200-NIGHTLY-Defy

**Comment by tpruvot** [comment] 2011-11-06 19:29
yea, i had to clean the full compile tree, its ok, will be fixed tomorrow :p

**Closed as completed by tpruvot** 2011-11-06 19:29 UTC

**Comment by tpruvot** [comment] 2011-11-08 05:40
this problem was with this commit : http://review.cyanogenmod.com/8603
