### ISSUE TITLE
Mp4 playback/ Video recording issues on RC1

### ISSUE THREAD

**Issue by vikrambharadwaj** [CyanogenDefy/android_device_motorola_jordan#26] opened 2011-06-26 13:56 UTC
Hi, Just flashed the RC1 and I see mp4 playback issues. Some videos are too jerky and unwatchable most of the times.
Videos recorded with the defy itself suffer from the same issue.

**Comment by ghost** [comment] 2011-06-27 07:24
I can confirm both the issues and say that the recording video frame drops it is a problem present from beta 6 version included.

**Comment by maniac103** [comment] 2011-06-27 08:24
Duplicate of #5.

**Closed as completed by maniac103** 2011-06-27 08:24 UTC

**Comment by ghost** [comment] 2011-06-27 08:40
Yes, if you speak about the mp4 PLAYBACK issue, but the RECORDING issue is still present from beta 6 so probably it is not related to the palyback issue now appears in RC1 and the link you post only talks about palyback issue.
