### ISSUE TITLE
Two BUGs of camera setting, RC1

### ISSUE THREAD

**Issue by arcol** [CyanogenDefy/android_device_motorola_jordan#27] opened 2011-06-26 16:12 UTC
1.advanced options -> Select "Long Focus" & "Search Button", The "Search Button" cannot work on "Long Focus"

2.advanced options -> Select "Volume Buttons Zoom", It works just "1x" and "6x", not "1x" to "6x" smoothly

**Comment by maniac103** [comment] 2011-06-27 08:21
1. is already in the works: http://review.cyanogenmod.com/#change,6315

**Comment by maniac103** [comment] 2011-06-27 08:26
Err, that meant to read item 2 is in the works, not item 1.

**Comment by maniac103** [comment] 2011-06-27 08:29
I will include item 1 in the mentioned patch as well.

**Comment by maniac103** [comment] 2011-06-29 08:38
Patch is merged now, thus the issue is fixed.

**Closed as completed by maniac103** 2011-06-29 08:38 UTC
