### ISSUE TITLE
Headset button: long press button doesn't work if screen is off

### ISSUE THREAD

**Issue by LeopardSurd** [CyanogenDefy/android_device_motorola_jordan#137] opened 2011-10-28 07:56 UTC
Hello, there is a little problem with calling using headset. If screen is off, I cannot end a call because to do that I need to do a long press on headset button that is not recognised by CM7 if the screen is off.

Thested with screen on, all is ok. During a call:
1. short press: mute the microphone
2. long press: end the call

Tested with screen off during a call:
1. short press: mute the microphone
2. long press: mute the microphone. (miss-recognised)

Also, apps like PlayerPro that use inbuilt headset button functions doesn't work correctly if screen is off. Only one single short press is recognised. Double, triple or long press are not recognised. 

The only app that by-pass this problem is Headset Button Controls (from Android Market) and it does that very good.

Anyway, clicks combinatons are not important but the long press for ending calls is an important in-build feature. Please, fix it. 

Thanks!

**Comment by maniac103** [comment] 2011-10-28 11:55
Duplicate of #118 - but not solved

**Closed as completed** 2011-11-11 11:16 UTC
Labels: Sensors

**Comment by tpruvot** [comment] 2011-11-11 16:12
fixed :
https://github.com/CyanogenDefy/android_frameworks_base/commit/82f9b34dd9408c8c52f1a3cb926dde652b45025c
